<?php

namespace Database\Factories;

use App\Models\Project;
use Illuminate\Database\Eloquent\Factories\Factory;

class GalleryFactory extends Factory
{
    public function definition(): array
    {
        return [
            'project_id' => Project::factory(),
            'name' => fake()->words(2, true).' Gallery',
            'description' => fake()->sentence(),
            'image_urls' => [
                'https://picsum.photos/seed/'.fake()->uuid().'/800/600',
                'https://picsum.photos/seed/'.fake()->uuid().'/800/600',
            ],
            // slug is auto-generated by Gallery::booted(), no need to set it here
        ];
    }
}
